service: serverless-siwe
frameworkVersion: '3'
provider:
  name: aws
  region: eu-west-1
  # Disable automatic rollback by CloudFormation on failure. To be used for non-production environments.
  disableRollback: true
  runtime: nodejs14.x
  memorySize: 128
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'

plugins:
  - serverless-offline
  - serverless-esbuild
package:
  individually: true
custom:
  esbuild:
    packager: yarn
    bundle: true
    minify: false
    sourcemap: true
    exclude: [ 'aws-sdk' ]
    target: 'node14'
    define: { 'require.resolve': undefined }
    platform: 'node'
    concurrency: 10
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002
functions:
  nonce:
    handler: src/functions/nonce.handler
    events:
      - httpApi:
          path: "/api/nonce"
          method: "GET"
  verify:
    handler: src/functions/verify.handler
    environment:
      NONCE_TTL: 10
    events:
      - httpApi:
          path: "/api/verify"
          method: "POST"
